INSERT INTO students (id, cod, nome, paed, turma, turno, serie, curso, modalidade) VALUES 
(401, '2053336', 'MATEUS SOARES DE OLIVEIRA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(402, '2168254', 'YASMIN YARA DE SOUZA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(403, '2515561', 'ANA GABRIELLY SANTOS OLIVEIRA DA SILVA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(404, '2512129', 'ALLYCE KETILLI DA SILVA PAULA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(405, '2526634', 'BEATRIZ GARCIA LIMPIAS SILVA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(406, '2518037', 'ANA VITÓRIA CRUZ PINHEIRO', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(407, '2531338', 'YAN PIETRO SANTOS SILVA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(408, '2533753', 'ZAID JONAS VILLARROEL RAMOS', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(409, '2548567', 'ISABEL RAFAELLY PINTO DA SILVA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(410, '2539796', 'BEATRIZ SOUZA MARQUES DA SILVA', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(411, '2515331', 'MARLON DOUGLAS BEZERRA DOS SANTOS', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(412, '2638118', 'VICTOR DE PAULA LORENZO BABESCO', false, '8º Ano B', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(413, '2528838', 'ISABELY RODRIGUES DE ANUNCIAÇÃO', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(414, '2518284', 'SAMUEL ROCHA MATOS', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(415, '2516934', 'VITÓRIA JESUS AGOSTINHA DA SILVA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(416, '2348246', 'GIOVANNA BRANDÃO SONAQUE', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(417, '2518661', 'HENNZO GABRYELL LIMA PEREIRA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(418, '2518644', 'HEVERTON LUCAS RODRIGUES BARBOSA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(419, '2438722', 'KAMILA VITÓRIA DE AMORIM COSTA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(420, '2188376', 'MARIA VICTÓRIA ARRUDA GOMES', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(421, '2517206', 'MIKAELLY SOFIA GONÇALVES MACHADO', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(422, '2517142', 'NICOLLAS SOUZA DE ALMEIDA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(423, '2516880', 'NIKOLLY CORRÊA GONÇALVES', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(424, '2516919', 'PEDRO HENRIQUE SILVA DE ALMEIDA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(425, '2518187', 'ADRYAN GUILHERME DE FREITAS SILVA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(426, '2513815', 'ANA VITÓRIA ALMEIDA DE ABREU CADINI', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(427, '2517524', 'BRUNA YASMIM RODRIGUES DE LIMA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(428, '2325241', 'DANILA SILVA DE JESUS', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(429, '2143754', 'DAVID ZEBALLO PORFIRIO DE DEUS', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(430, '2167800', 'THAUANE EVA SOUZA PEREIRA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(431, '2181253', 'ISADORA CRISTINA DA SILVA GAZIM', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(432, '2156926', 'JOHNNY MAURICIO DE SOUZA NEVES', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(433, '2297008', 'LUIZ FELIP AMORIN MUNIZ DA SILVA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(434, '2527683', 'SOPHIA APARECIDA PINHO GONÇALVES', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(435, '2548145', 'CARLOS DANIEL UNTAR MENDES COELHO', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(436, '2309298', 'WUANDERSON DE FIGUEIREDO E SILVA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(437, '2342574', 'IGOR LUZ DA COSTA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(438, '2461755', 'KAUANNY DOS SANTOS MARCOSKI', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(439, '2513228', 'OTAVIO GABRIEL DOS SANTOS ALMEIDA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(440, '2537443', 'ANTONIO CARLOS RODRIGUES DOS SANTOS', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(441, '2515734', 'ENZO FORLAN VIEIRA LANAS', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(442, '2172924', 'MANUELA HELENA DOS SANTOS', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(443, '2081678', 'MARIA CLARA DOS SANTOS VIEIRA', false, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(444, '2438683', 'DAVID CESAR SOBRAL FRANÇA', true, '8º Ano C', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(445, '2526985', 'LUCAS GABRIEL FRANÇA DE MORAES', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(446, '2528120', 'ÁDRIAN LUCAS ANTUNES SILVA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(447, '2526723', 'AMANDA MONTEIRO LISBOA SILVA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(448, '2631147', 'ANNA JULIA CAMPOS MOREIRA DA SILVA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(449, '2528420', 'ANTHONY GABRIEL DE MAGALHÃES MARQUES', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(450, '2517221', 'ARIADYNA VITORYA GARIBALDI DE SOUZA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(451, '2526594', 'CARLOS HENRIK DE MAGALHAES MARQUES', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(452, '2528320', 'CAUANY GABRIELE MARTINS DA SILVA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(453, '2139845', 'DAVI MAI PRADO', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(454, '2517747', 'DIANA RUBIAN NASCIMENTO SENE', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(455, '2518771', 'DILAN PATERNINA SANTOS', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(456, '2517224', 'EMILLY GABRIELLY CAMPOS PINHEIRO', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(457, '2164610', 'GABRIELLY VICTORIA DE JESUS DA MACENA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(458, '2518830', 'ISABELLY CRISTINA RAMOS CABRAL DE MELO', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(459, '2542497', 'JOÃO DAVY MENDES SILVA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(460, '2481678', 'JULIA GABRIELLY COSTA SANTANA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(461, '2517098', 'MARIA CLARA FONTES FONTOURA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(462, '2528056', 'MARIA HELLENA MUNIZ SANTANA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(463, '2517235', 'MARIA JULIA CRISOSTOMO MARIANI', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(464, '2527163', 'NAUANNY GABRIELLY DA SILVA DENIZ', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(465, '2518782', 'NICOLLAS RANGEL DE MOURA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(466, '2451603', 'RHUAN GUILHERME DA SILVA OLIVEIRA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(467, '2443494', 'YARA TAYNA ALVES DA COSTA PROENÇA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(468, '2397677', 'FELIPE AUGUSTO COSTA PIRES', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(469, '2518423', 'PEDRO HENRYQUE MORAES ESQUIVEL', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(470, '2518806', 'LUIZA KOMOLINE LIMA DE CAMPOS', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(471, '2141412', 'SARA ZARISTA VASCONCELOS', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(472, '2513609', 'KAUANY VITORIA OLIVEIRA DE SOUZA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(473, '2198622', 'ANELY CRYSTINE DA SILVA ALGARANHAES', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(474, '2733349', 'VICTORIA CAROLINE AGUETONI GOIS', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(475, '2173024', 'ANA CLARA CORREA GUMERCINDO', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(476, '2442208', 'SOPHIA THEODORA SAMPAIO SILVA', false, '8º Ano D', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(477, '2708162', 'PRISCILLA SÁ DA CONCEIÇÃO FRANÇA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(478, '2710052', 'RHUAN PEDRO DA CRUZ MAGALHÃES', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(479, '2534715', 'PAOLA ISABELLY DA SILVA BARBOSA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(480, '2531171', 'IZABELLY APARECIDA MORAIS DA SILVA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(481, '2529835', 'JESUS MISAEL RODRIGUES MARTINEZ', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(482, '2534458', 'JULIA EMANUELLY TELES DOS REIS', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(483, '2536482', 'LUCAS VIEIRA DE AMORIM', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(484, '2534092', 'LUYD GABRIEL DE SOUZA MOREIRA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(485, '2529087', 'MARIANA VITÓRIA OLIVEIRA DA SILVA RIBEIRO', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(486, '2531289', 'MIGUEL SEBASTIAN BATISTA BARRETO', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(487, '2515011', 'MIKAEL JOSE PACHECO', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(488, '2532715', 'NÍCOLLAS MORAES PAES DA CONCEIÇÃO', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(489, '2533324', 'ALANNA GABRIELLY DA SILVA GAMA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(490, '1933307', 'ANA BEATRIS DA COSTA SILVA', true, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(491, '2526024', 'ANA JULIA RODRIGUES LOURO', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(492, '2530888', 'ANA VITÓRIA MORAIS MOREIRA DA SILVA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(493, '2534351', 'BEATRIZ TAVEIRA BASTOS LARA DE CARVALHO', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(494, '2529575', 'ENZO GABRIEL LIMA PEDROSA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(495, '2097452', 'GABRIELA AYALA SOUZA SILVA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(496, '2174498', 'GABRIELLY VITORIA DA SILVA OLIVEIRA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(497, '2528984', 'ISRAEL REI RODRIGUES', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(498, '2383388', 'KETHELY VICTORIA LACERDA DE ALMEIDA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(499, '2552879', 'EMANOELLY STHEFANI XAVIER DE LIMA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(500, '2517544', 'ROGER KAUA LEMES DA SILVA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(501, '2531765', 'JULLYA GABRIELLY DE OLIVEIRA ELIAS', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(502, '2397931', 'PIETRO HENRIQUE GONCALVES DA SILVA FIORINI', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(503, '2513755', 'AYNNA VITORIA CHAVES CEZARIO DE SOUZA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(504, '2722771', 'GUILHERME CASTRO SOARES', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(505, '2609249', 'WESLEY DA SILVA RONDON', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(506, '2661507', 'JONNIEL DAVID BERMUDEZ ALCALA', false, '8º Ano E', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(507, '2544375', 'ALISON DA SILVA GOMES', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(508, '2558337', 'BIANCA VALDETE FERREIRA CARVALHO', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(509, '2540763', 'CARLOS GABRIEL RODRIGUES DE SOUZA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(510, '2539748', 'ELOM JOSÉ DA PALMA OGHINO', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(511, '2515135', 'GABRIEL PEREIRA NEVES', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(512, '2459633', 'GABRIEL ROLDÃO TABUAS', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(513, '2463240', 'JOÃO CARLOS LEITE MARQUES ASSUNÇÃO', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(514, '2180058', 'LUIZ FERNANDO SILVEIRA DOS SANTOS FACIM', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(515, '2334226', 'LUIZ HENRIQUE PADILHA FRANÇA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(516, '2567681', 'MANUELE VITÓRIA DA SILVA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(517, '2540427', 'MARIA FERNANDA MORAES DA SILVA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(518, '2457080', 'MARIA HELOISA CAMPOS DE OLIVEIRA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(519, '2564585', 'MATEUS DE PAULA LACERDA FERREIRA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(520, '2478054', 'PEDRO HENRIQUE DA CRUZ LIMA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(521, '2551323', 'RAYLA MONIQUE MARTINS FONTES', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(522, '2543421', 'STEPHANY SOFIA AMORIM DE ALMEIDA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(523, '2540506', 'THAWANY GABRIELLY DE SILVA OLIVEIRA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(524, '2620263', 'VINICIUS DA COSTA MANEIA FRANCISCO', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(525, '2517745', 'LUCIANA FREITAS GOMES', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(526, '2160102', 'ANA BEATRIZ MARIA DA SILVA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(527, '2515810', 'EDER HENRIQUE LARA CONCEIÇÃO DE OLIVEIRA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(528, '2518434', 'EDUARDO FERNANDEZ DE CARVALHO', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(529, '2585590', 'GABRIANE RAQUEL FERREIRA DE CAMPOS', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(530, '2517068', 'ISABELLY VALENTINA DA SILVA AMARAL', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(531, '2517077', 'ISADORA CATARINE DA SILVA AMARAL', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(532, '2530300', 'NIKOLAS HENRIQUE GOMES DO ESPIRITO SANTO', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(533, '2520648', 'ISABELA DANTAS SILVA', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(534, '2729237', 'ALICE SOUZA SAID', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(535, '2480120', 'JOSIVANE DE LIMA SOARES', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(536, '2345252', 'SAMUEL TYAGO DE ALMEIDA GONÇALVES', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(537, '2518650', 'ANA GABRIELA RONDON DO ESPIRITO SANTO', false, '8º Ano F', 'Vespertino', '8º Ano', 'Regular', 'Fundamental'),
(538, '2471542', 'KAUANY VITORIA BOANERGES DE CAMPOS', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(539, '2445246', 'EMILLY SAMIRA FRANÇA DE MORAES', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(540, '2348148', 'ARISLAINE DE SOUZA LIMA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(541, '2100504', 'CARLOS DANIEL SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(542, '2453826', 'HANTHONY LAERTE DA SILVA NASCIMENTO', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(543, '2454035', 'JONAS MAGNNUS DA SILVA GAUNA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(544, '2445434', 'KAIO AUGUSTO NEVES DA SILVA', true, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(545, '2382583', 'GABRIEL SILVA SANTANA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(546, '2535197', 'JANAINA MARTINS DA SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(547, '2471493', 'KELVYN SILVA DO ESPIRITO SANTO', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(548, '2465314', 'LUIZ FREDERICO SOUZA DOS SANTOS', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(549, '2090761', 'MARIA BEATRIZ ANUNCIAÇÃO DA SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(550, '2474091', 'MARIA JULIA DE MAGALHAES SENE', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(551, '2159990', 'JOAO PAULO PEREIRA MARQUES DA SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(552, '2443046', 'GIOVANNA NASCIMENTO DA SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(553, '2454621', 'GUILHERME HENRYQUE LEMES DOS SANTOS', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(554, '2445441', 'HUGO SILVA SANTOS', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(555, '2447813', 'JOANA VICTORIA DA SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(556, '2445543', 'JOÃO GUILHERME DO NASCIMENTO MARQUEZINI', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(557, '2454113', 'JOSÉ ANTÔNIO DA SILVA MORAES', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(558, '2445844', 'KAMILLY KELLY DA SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(559, '2451627', 'LUIS GABRIEL RAMOS DE ARRUDA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(560, '2071148', 'RAFAEL NATHAN MARQUES DA SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(561, '2292319', 'ANNA JULIA LISBOA DE OLIVEIRA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(562, '2463262', 'LETÍCIA MARIA DA SILVA SANTOS', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(563, '2445234', 'SAMUEL FERREIRA BAGLI', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(564, '2454135', 'GABRIEL GUILHERME MALDONADO DE PINHO', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(565, '2531226', 'DIOGO ABREU DE LUCENA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(566, '2718086', 'MARCOS MACIEL DOS SANTOS SILVA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(567, '2311596', 'KAUA HENRIQUE DE OLIVEIRA LIMA', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(568, '2444990', 'HELLENA SILVA DA CRUZ', true, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(569, '2639762', 'HENZO DANIEL SANTANA RODRIGUES', false, '9º Ano A', 'Vespertino', '9º Ano', 'Regular', 'Fundamental'),
(570, '2704941', 'CINTHYA MARIA DA SILVA LIMA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(571, '2412169', 'ABNER EMANUEL COELHO DA SILVA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(572, '2216062', 'ALESSANDRO GAMBAROTO PASTRO FILHO', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(573, '2453035', 'ALICE DE OLIVEIRA MARQUES MARCOSKI', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(574, '2450978', 'ANA JULIA SANTOS DA SILVA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(575, '2443708', 'ANA JULIA SILVA DE LIMA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(576, '2453852', 'CLÁUDIA CONCEIÇÃO DO ESPÍRITO SANTO', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(577, '2456496', 'EDUARDA CRISTINY SANTANA E SILVA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(578, '2454717', 'EDUARDA DA SILVA ALVES', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(579, '2463292', 'ENZO HENRIQUE DA COSTA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(580, '2445476', 'ERICK RUAN XIMENES ALMEIDA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(581, '2445243', 'ESTER CRISTINA CUNHA DOS SANTOS', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(582, '2443513', 'VITOR HUGO LACERDA DA SILVA SANTOS', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(583, '2443669', 'JULIA DE OLIVEIRA LIMA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(584, '2453950', 'JÚLIA DIAMANTE DA CRUZ', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(585, '2451272', 'KATRYNI VITORIA CORREA DE SOUZA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(586, '2447795', 'LARYSSA MARIA DE ALMEIDA SILVA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(587, '2248200', 'LUCAS DE DEUS OLIVEIRA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(588, '2526306', 'JOÃO ALEX MARQUES DE OLIVEIRA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(589, '2454149', 'LUCAS BORGES RODRIGUES DA SILVA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(590, '2456126', 'LUCAS STRASSBURGER DOS SANTOS', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(591, '2457389', 'LUKAS VINNYCIUS DUARTE SILVA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(592, '2459581', 'MATEUS STUY ROSADA', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(593, '2445239', 'JOAO LUCAS DA SILVA COSMO', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(594, '2445251', 'LAUANY PAOLA ESCOLASTICO MILAS', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(595, '2446356', 'MICKAELL FERNANDO DA SILVA GUERREIRO', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(596, '2445237', 'LUANNA FERNANDA GONÇALVES PORTO', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(597, '2451204', 'THAYNAN LARA MOREIRA ASSUNÇÃO', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(598, '2457231', 'ANA JULYA MARTINS DE ANUNCIACÃO', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(599, '2445459', 'IHIRPES GABRIELLY DOS SANTOS GALANTE', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(600, '2380591', 'VITORIA COELHO RODRIGUES', false, '9º Ano B', 'Matutino', '9º Ano', 'Regular', 'Fundamental') ON CONFLICT (id) DO NOTHING;

INSERT INTO students (id, cod, nome, paed, turma, turno, serie, curso, modalidade) VALUES 
(601, '2445226', 'MILENA MORAIS MORAGA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(602, '2475705', 'NAWANNY RODRIGUES CAITANO', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(603, '2445219', 'SOPHIA VITÓRIA NASCIMENTO DE MORAIS', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(604, '2445502', 'LAYS HELENA NASCIMENTO DE OLIVEIRA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(605, '2456308', 'MARIA LUIZA NASCIMENTO MARQUES', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(606, '2191799', 'MARIA SOPHIA SILVA DE MORAES', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(607, '2455993', 'MATHEUS LOPES GONÇALVES', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(608, '2459648', 'RAQUEL VITÓRIA MANOELE DA SILVA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(609, '2446400', 'SAFIRA VITORIA DA SILVA MENDES', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(610, '2450959', 'SOPHIA FERREIRA BARBOZA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(611, '2193862', 'THAYLA SUELLEN DE JESUS VIEIRA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(612, '2445836', 'WINNER GUSTAVO CAMPOS DE QUEIROZ', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(613, '2445603', 'ANDRESSA COUTO GERALDO', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(614, '2445448', 'ANNA FLÁVIA MENDES PEREIRA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(615, '2445252', 'ANNA JULIA RODRIGUES BOCUTI', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(616, '2459535', 'EMILLY VITORIA DIAS DE ALMEIDA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(617, '2445238', 'LUIS FELIPE DA SILVA CAMPOS', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(618, '2445218', 'MARIA EDUARDA FARIA DE OLIVEIRA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(619, '2053558', 'MATHEUS BOTELHO DA SILVA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(620, '2445236', 'RAFAELA APARECIDA IDELFONSO MORAES GUIA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(621, '2453980', 'SARA VITÓRIA NASCIMENTO DA SILVA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(622, '2454590', 'MARCOS VINICIUS RODRIGUES', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(623, '2463314', 'NIÉDSON CUNHA DA SILVA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(624, '2284106', 'MAYARA CLARA SOUZA DA COSTA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(625, '2211402', 'AMANDA CRISTINA DA SILVA RIBEIRO', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(626, '2445248', 'BIANCA GONÇALVES ALMEIDA DA SILVA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(627, '2463138', 'EMANUELLY CRISTINY DE CAMPOS SILVA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(628, '2279428', 'ANA LOUISE DA SILVA MORAES', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(629, '2727183', 'LUCAS QUERUBIM ALMEIDA TORRES', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(630, '2449251', 'MARIA ISADORA DANTAS DA SILVA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(631, '2464579', 'MIGUEL PAULO DO NASCIMENTO BUSARELLO', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(632, '2060244', 'WENDER NEVES DA COSTA', false, '9º Ano C', 'Matutino', '9º Ano', 'Regular', 'Fundamental'),
(633, '2710650', 'LUCAS GABRIEL DA SILVA BLOQUE', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(634, '1728983', 'APARECIDA SOUZA SANTOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(635, '2661920', 'DEBORA DE SOUZA SANTOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(636, '2447712', 'MARCELO EDUARDO CAMPOS DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(637, '2659128', 'VALDELANIA DOS REIS GOMES', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(638, '2052480', 'ISAIAS VANILDO DA SILVA FIGUEIREDO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(639, '2322855', 'NICOLAS GABRIEL ARRUDA MACIEL', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(640, '2321527', 'RAIANNE EVILLY SILVA FIGUEIREDO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(641, '1892470', 'DAVI RIBEIRO BRAGA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(642, '2218332', 'ALLANA KETILY MARTINS CAMPOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(643, '2281498', 'MARIA EDUARDA MARTINS DE CAMPOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(644, '2281483', 'MARIA FERNANDA MARTINS DE CAMPOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(645, '1975948', 'ROZENIRA PEREIRA DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(646, '1876313', 'MARCOS VINÍCIUS DE ALMEIDA MULLER', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(647, '2702268', 'KEROLLEM RAUANA DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(648, '2305413', 'ELLEN FLORENCIANO MARTINS DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(649, '2246098', 'VITOR GABRIEL SOARES DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(650, '2274901', 'PEDRO HENRIQUE RODRIGUES DE OLIVEIRA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(651, '1865924', 'LUANA VITORIA CLIVATI DOS SANTOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(652, '1437155', 'SILVANA MARIA DE JESUS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(653, '2549564', 'MARIANY MARTINS DUTRA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(654, '2371481', 'JOÃO GABRIEL BLUM DE JESUS SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(655, '2282008', 'ALCIDES SANTOS GOES SOARES', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(656, '2072667', 'MAYCOLN FERREIRA GONÇALVES', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(657, '2343742', 'JOÃO VITOR MAIA OLIVEIRA', true, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(658, '2404448', 'DAVI JUNIOR BARBOSA SANTOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(659, '1994427', 'KEVYN ADAILTON SOUZA GOMES', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(660, '2395361', 'ANA JULIA DE CAMPOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(661, '2275081', 'SIÃO ONÓRIO DA SILVA CAMPOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(662, '2281039', 'LUCAS GABRIEL OLIVEIRA MARQUES COSTA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(663, '2714996', 'ANTHONY GABRIEL SOUZA DE ARAÚJO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(664, '2715291', 'RAYLANE PIRES DO NASCIMENTO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(665, '2543589', 'ISADHORA MIKAELE SOARES MOTTA DE ALMEIDA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(666, '2262038', 'GEOVANA FABIANA PONCE DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(667, '385532', 'JESSICA ALVES DE SOUZA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(668, '2304220', 'LUAN PINHO DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(669, '2717250', 'CARMOS DA SILVA ALBUQUERQUE', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(670, '2718511', 'SANTIAGO RAFAEL ROCCA PALACIOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(671, '1933572', 'DAVID LUCAS DARCIS FERREIRA PRADO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(672, '2276433', 'MARCIO LUIZ CORREA CAMARGO RAMOS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(673, '1869571', 'JOÃO GABRIEL COSTA DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(674, '2238849', 'AJASMINNY VITORIA ELIAS DE ARRUDA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(675, '1496649', 'ISRAEL D''ORNELLAS CATARINO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(676, '2164192', 'CARLOS EDUARDO CANAPINI DE OLIVEIRA REIS', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(677, '2278452', 'GABRIEL SILVA SARUBBI', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(678, '2724908', 'GLEIDSON BRENO PEREIRA RODRIGUES', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(679, '2142433', 'VICTOR HUGO CONSTANTINO LEQUE BRUNO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(680, '2317206', 'EDUARDO VIANA ESCOBAR', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(681, '2235865', 'LAVIER ISOTTON DE MELO ROCHA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(682, '1799273', 'JOAO MARCOS NUNES BRANDAO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(683, '2361111', 'LARISSA TAYNARA BUENO PEREIRA NEVES', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(684, '2161213', 'ANDREI GABRIEL SANTOS ASSUNÇÃO', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(685, '2633370', 'EUGENIA GONÇALVES DA SILVA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(686, '2643940', 'ANDRÉ RUAN DE OLIVEIRA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(687, '1919868', 'MATHEUS EDUARDO COSTA DA SILVEIRA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(688, '2631483', 'KAYKEZEDEQUE DE SOUZA ARRUDA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(689, '2282389', 'SAULO DE TARCIS DA SILVA MENDES', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(690, '1976383', 'MARIA CLARA NEVES FERREIRA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(691, '2737285', 'ESTERLINE DAYSSIE BON', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(692, '2418097', 'SANTIAGO JOSE PLAZA MOYA', false, 'EJA 8º/9º', 'Noturno', 'EJA', 'Regular', 'Fundamental'),
(693, '2701997', 'GABRIELLY VITORIA DA SILVA SOUZA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(694, '2702172', 'KARINLAY SILVA DE FREITAS', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(695, '2374589', 'ENZO GABRIEL DA CRUZ MARQUES', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(696, '2702566', 'KAIO GABRIEL DO NASCIMENTO MARTINS', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(697, '2375825', 'KAIKE RYAN BRITES DE OLIVEIRA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(698, '2703102', 'DEBORA VICTORIA RABELO ZAGUINI', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(699, '2703391', 'ANA BEATRIZ NEVES DE OLIVEIRA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(700, '2370028', 'ANNY VICTÓRIA RODRIGUES DE ALMEIDA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(701, '2703938', 'ANA CLARA DA SILVA RESENDE', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(702, '2110126', 'MIGUEL DUARTE VERHALEN', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(703, '2374155', 'KAYO ANDRÉ FERREIRA MENDES', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(704, '2705388', 'ANA FLAVIA DA SILVA QUEIROZ', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(705, '2705918', 'RHIANNY LEMES DE JESUS', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(706, '2373740', 'PEDRO HENRIQUE GOMES VILELA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(707, '2370449', 'JULIANY BEATRIZ GOMES DE LIMA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(708, '2361202', 'GUSTAVO BORGES DE SOUZA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(709, '2399000', 'JOENEI RUMEIRO DE ALMEIDA SOBRINHO', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(710, '2707711', 'JDIELLY KAROLINE DOS SANTOS MARTINELLI', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(711, '2707720', 'JENIFFER KARINE DOS SANTOS MARTINELLI', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(712, '2708945', 'EDNALDO TEIXEIRA DE SOUZA JUNIOR', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(713, '2399204', 'ALICE ISABELI FERREIRA FERNANDES', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(714, '2403735', 'GUILHERME SOUTO CARVALHO DA SILVA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(715, '2710094', 'MARIA GABRIELE NOGUEIRA DA SILVA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(716, '2710142', 'CLAUDINEY DOMINGOS GONÇALVES JUNIOR', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(717, '2372873', 'JOSÉ MIGUEL FILHO GUSMÃO', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(718, '2276592', 'ANDRE DE MORAES COSTA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(719, '2729001', 'ANALICE ARRUDA DE SOUZA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(720, '2704268', 'VICTOR HUGO DA SILVEIRA STIVAL', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(721, '2393091', 'VITORIA FRANCISCA PEREIRA ALVES', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(722, '2633908', 'MARIA EDUARDA BARBOSA REIS', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(723, '2702597', 'DAVID RIKELMY DA SILVA MAIA', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(724, '2703426', 'JAMILLY VITÓRIA DE FRANÇA CAMPOS', false, '1º Ano Técnico Logística', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(725, '2383568', 'GABRIELLE GARCIA PRUDENCIO', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(726, '2371362', 'EMILLY MARIA DE OLIVEIRA VIDAL', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(727, '2246688', 'KAUA HENRIQUE CAMPOS ALVES', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(728, '1970706', 'LUIS OTAVIO BUENO DA SILVA SOBRINHO', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(729, '2361770', 'MATHEUS LUCAS LOPES DE MORAIS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(730, '2531282', 'PABLO HENRIQUE RODRIGUES DE SOUZA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(731, '2380626', 'PEDRO HENRIQUE ALMEIDA DE MORAIS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(732, '2395094', 'SILAS DA SILVA MATIAS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(733, '2379618', 'ANDRESSA VITÓRIA HENRIQUE FERREIRA DOS SANTOS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(734, '2459731', 'FELIPE CARVALHO DA SILVA JUNIOR', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(735, '2368698', 'GABRIELA DA SILVA BEZERRA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(736, '2379732', 'GUSTAVO DUARTE DE OLIVEIRA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(737, '2395326', 'KAICK LOPES LEMES', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(738, '2380694', 'LUCAS IAGO DA SILVA ALBUQUERQUE', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(739, '2454008', 'MARIO JUNIOR ALVES DA ROCHA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(740, '2380633', 'SAMIRA GOES SOARES FERREIRA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(741, '2380871', 'DANILO MARTINS DE CAMPOS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(742, '2386075', 'FELIPE GABRIEL DE PAIVA ROSA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(743, '2361708', 'JOÃO VICTOR SANTOS DA CUNHA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(744, '2417593', 'LUCIANO HENRIQUE NEVES DA SILVA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(745, '2146336', 'THALES MIGUEL BESSA CAMPELO DE OLIVEIRA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(746, '2364721', 'THAYNA KAMILA MENEZES MENDES', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(747, '2383580', 'VITOR GABRIEL CUNHA DIAS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(748, '2380940', 'ALEXANDRE VITOR FONTES PAULO', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(749, '2379692', 'ARTHUR HENRIQUE SILVA DANTAS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(750, '2380919', 'ELIÉDER VINÍCIUS OLIVEIRA DA SILVA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(751, '2380709', 'VITORIA MENDES DE JESUS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(752, '2631623', 'THAYLLA CRISTINY COSTA FLECK', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(753, '2379685', 'DIOGO DA SILVA ROCHA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(754, '2574899', 'RAFAELLY JULIA CHESSMAN DA SILVA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(755, '2374213', 'ANA BEATRIZ SILVA DE MORAIS', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(756, '2727085', 'GABRIEL JUNIOR BOM DESPACHO SANTOS DA SILVA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(757, '2283947', 'ANA JULIA DA SILVA OLIVEIRA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(758, '1884503', 'CHRISTIAN DE SOUSA COSTA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(759, '2372789', 'LIBINI JAIANI DIAS GAMA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(760, '2735638', 'JOÃO GABRIEL AMORIM DE SOUSA', false, '1º Ano Linguagens A', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(761, '2706605', 'RAIANNY THAMARA SIQUEIRA SILVA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(762, '2379662', 'ARLON FARIA DE MORAIS', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(763, '2280384', 'BRENDA GABRIELY MONTEIRO MENDES', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(764, '2459132', 'CARLOS EDUARDO DE ALMEIDA CAMPOS', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(765, '2380968', 'DOUGLAS RYAN SANTANA RAMOS', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(766, '2380981', 'ELOISE ARRUDA MORAES', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(767, '2364070', 'GUILHERME HENRIQUE SANTOS DE CAMPOS', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(768, '2381040', 'GUILHERME WILLIAN RODRIGUES MARTINS XAVIER', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(769, '2071190', 'JOÃO RIBEIRO DE OLIVEIRA NETO', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(770, '2382470', 'RAFAEL AUGUSTO DE FRANÇA SILVA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(771, '2454800', 'RIHANA SOPHIA DE OLIVEIRA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(772, '2382278', 'YASMIN FERNANDA CUNHA MAGALHÃES', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(773, '2386039', 'ARIANY KARINY DE PAIVA ROSA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(774, '2021629', 'GABRIELLY RODRIGUES PIMENTEL', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(775, '2197973', 'ISABELLA MANEIA VITORIO', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(776, '1997969', 'KAIO ALEXANDRE UNTAR DOS SANTOS', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(777, '2309840', 'KAMILLY VITORIA DE QUEIROZ PEREIRA', true, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(778, '2373451', 'LIVIA ESTEFHANY MENEZES DA SILVA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(779, '2377288', 'NAYARA PEREIRA DE SOUZA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(780, '2380885', 'ALYNNE COSTA DE OLIVEIRA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(781, '2377111', 'HENRIQUE AUGUSTO MORAES DE MAGALHÃES', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(782, '2380107', 'ISABEL MENDES SILVA CARDOSO', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(783, '2620175', 'EVANDRO OLIVEIRA DE CARVALHO', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(784, '2386111', 'FERNANDA MARQUES LEMES', true, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(785, '2386026', 'ISABELY KAROLINY DE PAIVA ROSA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(786, '2365340', 'KAMILLY VITORIA PEDROSO DA SILVA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(787, '2156882', 'KETHILLY DE SOUZA NEVES', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(788, '2379786', 'LUAN YURI DE SOUZA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(789, '1976368', 'OTAVIO GARCIA DE ALMEIDA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(790, '2387142', 'RUAN CARLOS DA SILVA DIAS', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(791, '1996907', 'IKARO VITOR BARROS DE SOUZA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(792, '2439743', 'RHAYZON DIEGO MORAIS DE SOUSA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(793, '2304582', 'MAYSA DOS SANTOS TRINDADE', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(794, '2645582', 'OTAVIO SILVA BATISTA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(795, '2361702', 'RAQUEL MACHADO DA SILVA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(796, '2332977', 'NOEMY PEROLLA FREITAS DE SOUZA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(797, '1995900', 'BYANCA EVELYN DA SILVA SOUZA', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(798, '2572384', 'JULIO CÉSAR PEREIRA FORTES', false, '1º Ano Ciências Humanas B', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(799, '2701332', 'EMANUELLY VITORIA PEREIRA DE MELO', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(800, '2701668', 'CARLOS EDUARDO DE ALMEIDA CAMPOS', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio') ON CONFLICT (id) DO NOTHING;

INSERT INTO students (id, cod, nome, paed, turma, turno, serie, curso, modalidade) VALUES 
(801, '2701847', 'JOÃO PEDRO ROCHA DE LIMA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(802, '2701996', 'CLEYTON EDUARDO JESUS DA SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(803, '2374727', 'MARIA EDUARDA CORREA DA SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(804, '2704387', 'BRENO DIOGO SAAR TARIFA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(805, '2706178', 'LORRAYNE VITÓRIA CLEMENTE DA COSTA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(806, '2706705', 'MARIA HELOISA CLEMENTE DA COSTA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(807, '2306487', 'BRENDA CHRISTINA ALVES SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(808, '2379650', 'CLEVERSON LUCAS LIMA DA COSTA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(809, '2381029', 'DAFNY VICTORIA DE LIMA PIMENTA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(810, '2337460', 'ÉRLLON GUILHERME DE FREITA FERNANDES', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(811, '2364680', 'GABRIEL DEZAN RODRIGUES', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(812, '2361790', 'ISABELLY FERREIRA MESQUITA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(813, '2090625', 'JULIA AMANDA RODRIGUES DA SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(814, '2365940', 'GABRIEL PINHEIRO SANTOS', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(815, '2397003', 'HENRIQUE GABRIEL NUNES DE MIRANDA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(816, '2380540', 'JOÃO PEDRO TEIXEIRA DE LIMA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(817, '2361599', 'LORRAINY GABRIELY DO NASCIMENTO SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(818, '2396315', 'MIGUEL ARAÚJO GORGONHA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(819, '2380069', 'FELIPE GABRIEL DE ARRUDA LIMA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(820, '2360675', 'ISABELLA MARIA MARTINS CHIMENES', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(821, '2387158', 'MARIA FERNANDA LIMA PEREIRA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(822, '2382599', 'KETLYN VITORIA DA SILVA COSTA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(823, '2446807', 'LUCAS DA COSTA MANEIA GONÇALVES', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(824, '2301697', 'PAULLYNY GABRIELLY RIBEIRO DE ARAUJO', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(825, '2380094', 'YASMIM EDUARDA FERREIRA COSTA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(826, '2531049', 'KAUÃN HENRIQUE NILO DE AQUINO LEMES DO NASCIMENTO', true, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(827, '2370739', 'ANA LIA DA COSTA GOMES PEREIRA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(828, '2716683', 'GUSTHAVO HENRICK ALVES FERREIRA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(829, '2363961', 'SHIVANO HENRIQUE REIS DA SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(830, '2007506', 'POLYANA DE SOUZA LOPES', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(831, '2473984', 'ANA JULIA MACHADO LEMES', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(832, '2368977', 'MAIARA CRISTYNA DA SILVA BUENO', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(833, '2373877', 'LUIZ OTAVIO ALMEIDA SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(834, '2439469', 'GRASYELLY BARBOSA BATISTA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(835, '2543198', 'RIHANNA PEREIRA SILVA', false, '1º Ano Ciências da Natureza C', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(836, '2364368', 'LEONEL FERNANDO DENIZ PEREIRA DE CAMPOS', true, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(837, '2359676', 'HENZO JUAN RONDON NASCIMENTO', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(838, '2369718', 'LUCAS GABRIEL DO NASCIMENTO CORDEIRO', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(839, '2707270', 'KAMILLI VITORIA DE SOUZA ALMEIDA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(840, '2472983', 'JOÃO GABRIEL CAMPOS MOREIRA DA SILVA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(841, '2465128', 'GABRYELLA COSTA CAMPOS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(842, '2360552', 'KENAY ROCHA DOS SANTOS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(843, '2708765', 'VITÓRIA RAISSA NOGUEIRA DE CAMPOS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(844, '2708962', 'ISABELLY QUEIROZ DA SILVA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(845, '2709019', 'LYEDSON RODRIGUES DA SILVA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(846, '2709122', 'WENDRIANE SILVA DA COSTA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(847, '2382350', 'VITORIA FERNANDA PRADO SANTANA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(848, '2295590', 'LUCAS PAES ZARDO', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(849, '2706947', 'NATHALLIA GABRIELA OLIVEIRA DA SILVA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(850, '2493315', 'GABRIEL DE MORAES WEBER', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(851, '2277865', 'GABRIEL DE PAULA LACERDA FERREIRA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(852, '2246175', 'JOSÉ HENRIQUE PEREIRA RODRIGUES DOS SANTOS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(853, '2442664', 'KENNYD GABRIEL DA SILVA CUNHA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(854, '1960770', 'JEFERSON ZEBALLO PORFÍRIO DE DEUS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(855, '1770161', 'KAUÊ DE SOUZA SILVA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(856, '2371847', 'ANDRESSA CRISTINA DE AMORIM MAGALHÃES', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(857, '1898018', 'YARA ENGELS CASTAGNO GODOI', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(858, '2563046', 'KENNYD MARQUES COSTA GUIA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(859, '2705641', 'BRUNNO OTAVIO FORTES MARTINS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(860, '2383583', 'FELIPE RONALDO MAGALHAES DE LIMA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(861, '2382676', 'MARIA CLARA DE OLIVEIRA MORAIS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(862, '2230823', 'KALBERT FERREIRA LOPES', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(863, '2245081', 'GABRIELLA APARECIDA OLIVEIRA PINHEIRO DOS REIS SILVA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(864, '2296178', 'EMILLY PRISCILLA BRAGA GAIVA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(865, '2444325', 'ALESSANDRO DE SOUZA FIGUEIREDO', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(866, '2361487', 'DENNE JUAN DE LIMA MACIEL', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(867, '2362903', 'LUIS OTAVIO DA SILVA COSTA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(868, '2721616', 'SARAH EVANGELINA DE MATOS SIQUEIRA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(869, '2234038', 'CHRISTYAN ANDREZ CASTEDO PIRES', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(870, '2365957', 'LUIS EDUARDO LIMA PASQUALOTTO', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(871, '2371282', 'YUDY GABRIEL GOMES DIAS', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(872, '2276183', 'ANA KAROLINE GIOCONDO', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(873, '2395865', 'JOÃO EVANGELISTA DE ARRUDA NETO', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(874, '1961691', 'DIRCEU VESCOVI DE OLIVEIRA', false, '1º Ano Ciências da Natureza D', 'Matutino', '1º Ano', 'Médio', 'Médio'),
(875, '2361730', 'SABRINA MARTYN CAMANHO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(876, '2633538', 'ANTONIA MARCIEL DE JESUS', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(877, '2151729', 'DIEGO WILKRE DIAS SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(878, '2362889', 'HEVELLYN VITÓRIA DA SILVA GOMES', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(879, '368512', 'LUANA BATISTA DA SILVA MATEUS', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(880, '2395516', 'LUCAS GABRIEL ALMEIDA ALVES', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(881, '1135598', 'MARCELO DA SILVA MAGALHAES', true, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(882, '1908757', 'MARILDA ROBERTO DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(883, '2639175', 'SUELEN DOS SANTOS MAIA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(884, '1702722', 'VITORIA EMANUELLY PEREIRA DE MORAIS', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(885, '2231395', 'GABRIEL CARVALHO DE LIMA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(886, '1462679', 'KAUANY GABRYELLY GARCIA DE LIMA ROQUE', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(887, '1499366', 'REGINALDO DE ARAUJO SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(888, '2126883', 'ANA JULIA DA SILVA RIBEIRO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(889, '1764886', 'PABLO GADYEL EVANGELISTA DE JESUS', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(890, '2406470', 'LIVIA GEOVANNA DE OLIVEIRA BARBOSA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(891, '2444899', 'GUILHERME DA SILVA MACHADO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(892, '2382629', 'AGHATA LORAYNE GARIBALDI DE OLIVEIRA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(893, '2242862', 'VITORIA DA SILVA ALMEIDA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(894, '2637339', 'HENRI ALVES RODRIGUES', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(895, '2714250', 'DANILO LOPES FREITAS', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(896, '2274932', 'JOÃO PEDRO RODRIGUES DE OLIVEIRA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(897, '2242800', 'MATHEUS DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(898, '2222081', 'LUÍSA MARTINS DE AQUINO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(899, '2055845', 'VICTOR HUGO GONÇALVES VENTURA BORGES SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(900, '2314247', 'RIQUELME DIOGO RIBEIRO DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(901, '2212181', 'ANTHONY KLEBER DINIZ ANICETO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(902, '2720178', 'KAIO LAION AUGUSTO GONÇALO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(903, '2052279', 'LUANA DIAS DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(904, '2201729', 'EDUARDO HENRIQUE RODRIGUES PLETSCH', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(905, '2543902', 'ISABELLY RARWMY AMORIM DE ALMEIDA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(906, '2216228', 'KAUÃ FELLIPE RODRIGUES DE OLIVEIRA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(907, '2117458', 'RAFAEL PRESTES DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(908, '2277027', 'KAYRON DE CAMPOS CARVALHO RIBEIRO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(909, '2571608', 'REBECA DE SOUSA CORDOVIL', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(910, '2521867', 'HELLENA VYTORIA ROSA DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(911, '2363144', 'RAYKA TAYQUE MAGALHÃES DELAMAR', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(912, '2234938', 'GUSTAVO HENRIK DE CAMPOS OLIVEIRA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(913, '2361486', 'ELIEL GUILHERME SILVA DE MORAES', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(914, '2306544', 'GABRIEL FELIPE CUNHA RONDON', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(915, '2438824', 'MATEUS SANTOS OLIVEIRA DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(916, '2001992', 'ELYAKIM ANGUS RODRIGUES DE FREITAS GAMARRA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(917, '2344856', 'ESTHER ESPERANZA DIAZ MARQUEZ', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(918, '1960022', 'RUAN AUGUSTO BRITO AMORIM', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(919, '2493122', 'ISABELLY CAMPOS DA SILVA', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(920, '2379810', 'RAFAELA VITORIA MORAES', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(921, '2175134', 'LUIS ADELINO OLIVEIRA MARTINS PEDROSO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(922, '2418614', 'ERIKA EMILY MARQUES DO ESPIRITO SANTO', false, '1º Ano Noturno F', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(923, '2384373', 'VICTOR HUGO DA COSTA CABRAL SAMPAIO', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(924, '2288641', 'WILLITA FERNANDA RAMOS SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(925, '2702888', 'FABRICIO PINHEIRO DE JESUS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(926, '2380853', 'CREUNANDA FERREIRA MOREIRA DE SOUZA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(927, '2366030', 'HOESLAN DE ARAUJO FERREIRA LOPES', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(928, '2297430', 'VITOR GABRIEL DA SILVA MENDES', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(929, '2464573', 'CAROLAYNE ISABELLI DA SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(930, '2279172', 'JOSÉ AUGUSTO DE ALMEIDA COSTA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(931, '1750450', 'PEDRO PAULO AFONSO SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(932, '2404200', 'LUCIANO GABRIEL PLACIDO RODRIGUES', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(933, '2137276', 'VICTOR GABRIEL LEMES RODRIGUES', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(934, '1579475', 'JANILSON ALVES DE BRITO', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(935, '2361779', 'JOÃO PEDRO LOPES DE CAMPOS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(936, '2199005', 'JOÃO PEDRO PORTES BALDOINO', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(937, '2719316', 'KASSYO RODRIGUES DA SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(938, '2395161', 'KAUANI MORAIS PENHA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(939, '2603269', 'KAWANNY RODRIGUES DA SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(940, '2297210', 'LUCAS GABRIEL MIRANDA DE ALMEIDA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(941, '2109689', 'MARIANA EDUARDA GUIMARÃES CANABARRO', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(942, '2072439', 'RANNIELLY KETILLY SILVA FIGUEIREDO', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(943, '2712641', 'ROBERT ANTONIO DA SILVA MARQUES', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(944, '2258462', 'VICENTE JOSÉ ANTUNES NETO', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(945, '2328494', 'VICTOR HUGO GONZAGA NUNES', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(946, '2445758', 'KAUÃ VINYCIUS AMORIM OELKE', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(947, '1897926', 'KARLOS EDUARDO GONÇALVES DOS SANTOS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(948, '2379717', 'JONILSON NASCIMENTO FONTES', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(949, '2549710', 'WAGNER LOPES DE FREITAS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(950, '2685096', 'ANA VITORIA DOS SANTOS SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(951, '2274979', 'BRUNO WILLIAN LOPES SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(952, '2308322', 'DIENEFER MARIA DA COSTA BARROS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(953, '2362711', 'GUILHERME AUGUSTO DA SILVA OLIVEIRA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(954, '2395178', 'GUSTAVO SOUZA MESQUITA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(955, '2362839', 'HERIC FELIPE PINHEIRO DOS SANTOS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(956, '2710464', 'IGOR LUIZ ANTUNES AMORIM', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(957, '2375714', 'EVELLY CRISTHINA GONÇALVES DA SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(958, '2292835', 'NICOLAS GABRIEL CONRADO', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(959, '2276743', 'MARCOS DAVI SANTOS SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(960, '2444478', 'RANIELLY CONCEIÇÃO MORAES SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(961, '2313866', 'WELLYSON VIEIRA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(962, '2624445', 'DOUGLAS RODRIGUES SANTOS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(963, '2362370', 'YGOR ALESSANDRO SILVA SANTOS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(964, '2277675', 'MARIA JULIA DE OLIVEIRA MOYA DA COSTA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(965, '2010639', 'LUCAS GABRIEL SILVA BEZERRA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(966, '2339061', 'ADRIEL ALMEIDA SILVA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(967, '2465031', 'ANGEL MOISES BERRIOS ZORRILLA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(968, '2100970', 'EDUARDO GAMBARINI RIBEIRO PEREIRA', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(969, '2365300', 'LEIRIANNE VIANA DE JESUS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(970, '2646108', 'DANIEL SANTOS MORAIS', false, '1º Ano Noturno G', 'Noturno', '1º Ano', 'Médio', 'Médio'),
(971, '2598425', 'JHON CARLOS RODRIGUES DA SILVA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(972, '2338349', 'MATHEUS HENRIQUE DE SOUZA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(973, '2276955', 'ESTELLA CRISTINA CUNHA DOS SANTOS', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(974, '2308245', 'CARLOS EDUARDO COSTA MAIA ARRUDA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(975, '2275289', 'ERICK LEITE DE PAULA GONÇALVES', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(976, '2597976', 'GIOVANE PEDROSO DA SILVA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(977, '2275231', 'GLASIELLY RODRIGUES DUARTE', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(978, '2276196', 'HEVELLIN HANANDA NEVES GILGLIOLI', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(979, '2274658', 'LARISSA CRISTINA DO NASCIMENTO MORAIS', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(980, '2274738', 'PEDRO HENRIQUE PEREIRA CAMPOS', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(981, '2275142', 'SAMUEL THAYLISON DE JESUS VIEIRA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(982, '2276858', 'ALANNY VICTORIA MENDONCA E SILVA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(983, '2313101', 'ANA SOFIA RODRIGUES DA ROSA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(984, '2176145', 'ANA SOPHIA RODRIGUES MORAIS SCHREDER', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(985, '2276077', 'ANGELINA CRISTINA BEZERRA RODRIGUES', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(986, '2313075', 'FELYPE GABRIEL DA SILVA', true, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(987, '2276660', 'NICOLY SOFIA DE BARROS', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(988, '2278577', 'AMANDA CRISTINA DA SILVA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(989, '2146419', 'ANNA KAROLLINY CAMPOS DE SOUZA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(990, '2275276', 'ARTHUR DE AZEVEDO FRANÇA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(991, '2626331', 'BHEATRIZ VITÓRIA DOMINGUEZ DOS REIS', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(992, '2628818', 'ELLEN VICTORIA RODRIGUES SANTOS', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(993, '2248396', 'JAINNY VIEIRA DA CRUZ', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(994, '2278374', 'LETICIA RENATA BOTELHO CURVO', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(995, '2278434', 'MARCIELE CAMPOS MORAIS', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(996, '2300386', 'MARIA CLARA BARROS GARCIA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(997, '2276016', 'MAYSA GABRIELLY DE SOUZA SALES', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(998, '2278387', 'NATHÁLIA GABRIELLY ALMEIDA DA SILVA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(999, '2110573', 'KEMILLY GABRIELLY DA SILVA E SILVA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1000, '2307176', 'NATHALIA ORMOND DE SOUZA NOGUEIRA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio') ON CONFLICT (id) DO NOTHING;

