INSERT INTO students (id, cod, nome, paed, turma, turno, serie, curso, modalidade) VALUES 
(1001, '2300460', 'GUILHERME BRAGA NEVES', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1002, '2313573', 'HELOA TRINDADE TEIXEIRA', false, '2º Ano Linguagens A', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1003, '2713259', 'JOAO CARLOS MUNIZ DE SOUZA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1004, '1814431', 'CAUAN ERICK FERREIRA DE OLIVEIRA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1005, '2242932', 'SOPHIA RAIANNY MAXIMINIO COSTA UREBÊ', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1006, '2400246', 'MARIA EDUARDA DE SOUZA MIRANDA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1007, '2136458', 'SAMILY SANTANA DE ARRUDA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1008, '2046607', 'ANA CLARA DE ARRUDA SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1009, '2156138', 'PABLO APARECIDO DE CAMPOS PEREIRA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1010, '1933630', 'GUILHERME FERREIRA LOPES', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1011, '2260982', 'JOSÉ LEONARDO LEMES DA SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1012, '2246640', 'LUIZ GUILHERME DE ALMEIDA SANTOS', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1013, '2259483', 'GRASIELE NEVES SANTANA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1014, '2223296', 'GABRIELA CRISTINA MARTINS DA SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1015, '2161858', 'GUILHERME TILLWITZ LIMA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1016, '1697373', 'ÉRIKA JOVANNA CAMPOS DA SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1017, '2276671', 'ANA LUIZA DA SILVA SANTOS', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1018, '2284240', 'GUSTAVO SOUTO CARVALHO DA SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1019, '2292586', 'PAULO RUBENS RAMIRES NETO', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1020, '1175134', 'CLEIDIANE MARQUES SILVA SOUZA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1021, '2444492', 'RAÍ HENRIQUE ARRUDA DO NASCIMENTO', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1022, '1727669', 'FERNANDA ALMEIDA GOMES NUNES', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1023, '1060668', 'SILVANA JESUINA DA SILVA PORTO', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1024, '2051031', 'EDSON FILHO DA CRUZ SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1025, '2399462', 'MATHEUS SILVA NUNES', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1026, '2361177', 'RUAN LUCAS LOPES DE ALMEIDA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1027, '2071448', 'LUIZ GUSTAVO DE AMORIM SANTOS', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1028, '2225507', 'EMANOELE JESUS DA SILVA DOURADO', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1029, '2066893', 'JONAS GABRIEL RIBEIRO DE ARAUJO', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1030, '1782250', 'MONICA VITORIA DE ARAUJO ALVES', true, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1031, '2245705', 'LUÍS AUGUSTO ALMEIDA CAMPOS', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1032, '2050763', 'CARLOS RENAN DA SILVA ROSA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1033, '2167186', 'ANDRÉ SANTOS SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1034, '2238774', 'ANNY ISABELLY LEMES BATISTA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1035, '2298640', 'CHRISTOPHER KAWAN DA SILVA ARAUJO', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1036, '2549714', 'PEDRO HENRIQUE SILVA DE FREITAS', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1037, '2265115', 'DISLENE SOUZA LEMES', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1038, '366578', 'FRANCIELE DA SILVA', false, '2º Ano PRA A', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1039, '1709804', 'EDUARDO PINHEIRO DE JESUS', false, '2º Ano PRA B', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1040, '2045558', 'JENNYFER CAMILLY ANTUNES UMENO', false, '2º Ano PRA B', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1041, '2278618', 'IASMIN CAROLINE DE OLIVEIRA', false, '2º Ano PRA B', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1042, '1333136', 'ROSALINA ALVES DE SOUZA', false, '2º Ano PRA B', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1043, '2260911', 'ANDERSON HENRIQUE CAMPOS SANTOS', false, '2º Ano PRA B', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1044, '2311323', 'HELOÍZA SANTOS CAVANHA', false, '2º Ano PRA B', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1045, '2456949', 'AVYLLA NORATO BALDEZ', false, '2º Ano PRA B', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1046, '2620126', 'KLEBER ANDRADE SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1047, '2065706', 'VITÓRIA APARECIDA PORTUGAL DE OLIVEIRA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1048, '2624649', 'KHAYKE ALEXSSANDER DOMINGUEZ SILVA BATISTA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1049, '2597081', 'HEMANOELE LIMA DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1050, '2273850', 'HELOISY KHAWANNY GONÇALVES DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1051, '2603413', 'PABLO CRISTHYAN DE OLIVEIRA CRUZ', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1052, '1781240', 'WENDEL BRÊDA MUSACCHIO ANTUNES', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1053, '2631737', 'DAFNY VITORIA DA SILVA SOUZA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1054, '2136383', 'DANIELI NASCIMENTO DAS NEVES', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1055, '2362712', 'KAIO GUILHERME RODRIGUES MARQUES DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1056, '2362464', 'KAUÃ FELIPE SANTOS DA CRUZ', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1057, '2601588', 'KAUANNY VITÓRIA DE SANTANA MACIEL', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1058, '2626730', 'KEMILLY KIARA LIRA DO NASCIMENTO', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1059, '2621066', 'LUCAS VINICIUS MOREIRA VASCONCELOS', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1060, '2601828', 'MARIANE DE ABREU MENDES', true, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1061, '2601236', 'NAUANY FERREIRA DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1062, '2625919', 'PEDRO HENRIQUE BARBOSA BRANDÃO', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1063, '2631034', 'PEDRO HENRIQUE SILVA BATISTA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1064, '2601719', 'SUELE NUNES FORTES', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1065, '2625661', 'VICTOR HUGO DE LIMA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1066, '1877524', 'ARTHUR RODRIGUES PACHECO', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1067, '2597070', 'DANIEL PERIS LAURENTINO FORTES', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1068, '2467489', 'PAULO JUNIOR DA COSTA FRANÇA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1069, '2252996', 'TIAGO DE JESUS BATISTA DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1070, '2604047', 'MONIKE LORRAYNE DA SILVA SOUZA', true, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1071, '2278294', 'LYARA THIEMI TAKADA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1072, '2159891', 'ANNA VICTORIA DE ARRUDA DUARTE', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1073, '1991641', 'DAVI OTAVIO ARRUDA DE DEUS', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1074, '2244158', 'JOÃO PEDRO GONÇALVES DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1075, '1754819', 'SAMUEL DE ASSIS DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1076, '1747982', 'KELVIA VITORIA FERREIRA DA SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1077, '2393010', 'ANA JULIA PADILHA GUIMARÃES', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1078, '2246088', 'GABRIELLY SANTOS SILVA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1079, '2276988', 'MAISA PERTILE DA CUNHA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1080, '2082465', 'JACKSON DOUGLAS DA CRUZ CORREA', false, '2º Ano Linguagens B', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1081, '2596307', 'MARIA HELENA COPERTINO DA SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1082, '2273763', 'LETICIA CARDOSO MIRANDA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1083, '2221188', 'ANI ELLY SILVA DE ALMEIDA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1084, '2276838', 'ELLOÁ VICTORIA MENDONÇA E SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1085, '2601447', 'ESDRAS KIAN MAIDANA MARTINS DA SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1086, '2048176', 'FELIPE LEONARDO FRANCA FREITAS', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1087, '2362190', 'KHANANDA MARYANNA DA SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1088, '1886879', 'LUIZ DA SILVA VINHAIS', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1089, '2274780', 'MARIANY CINTHIA SOUZA DA SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1090, '2329185', 'THÁBATA DUARTE OLIVEIRA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1091, '2303581', 'VANDREI FELIX DA SILVA SOUZA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1092, '2599621', 'WALBER BENEDITO EVANGELISTA DE OLIVEIRA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1093, '2274717', 'ANA LUÍZA MORAIS ALVES', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1094, '2000626', 'ANNA ALICE POMOCENO MARQUES DA SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1095, '2354031', 'EDWERYGNNER AMORIM PEREIRA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1096, '2015063', 'EMILLY MANOELY SIQUEIRA RODRIGUES', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1097, '2282093', 'GABRIEL JABERS FEITOSA DE MORAIS', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1098, '2603934', 'JOÃO PEDRO ALVES DE ANDRADE', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1099, '2383753', 'KAUANY FAISTINGUER FARIAS', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1100, '2601127', 'LUDYMILA JENNYFER FORTES DE OLIVEIRA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1101, '1879910', 'LUIZ GUILHERME FERRAZ LEMES DA SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1102, '2278411', 'NATHALIE KAROLINE CRUZ AMARAL', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1103, '2601505', 'PEDRO HENRIQUE SANTOS DE ARRUDA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1104, '1931891', 'JARDES ANTONY OLIVEIRA MOREIRA SOUZA DA SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1105, '2603804', 'AMANDA DOS SANTOS COSTA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1106, '2152291', 'ANA CLARA DE CAMPOS BARROS', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1107, '1995959', 'IAN PEDRO RIBEIRO MENDES', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1108, '1974039', 'WANDERLEY DA SILVA RONDON', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1109, '2549636', 'REINALDO SANTOS ABREU DE OLIVEIRA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1110, '2089014', 'ISABELLY BOABAID PEREIRA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1111, '2275204', 'BRUNO ISAAC DE SÁ SILVA', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1112, '2299569', 'VINICIUS HENRIQUE FRANÇA DELUQUI', false, '2º Ano Ciências Humanas C', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1113, '2290819', 'BRUNO VALCI DA SILVA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1114, '2276168', 'ERICK GUSTAVO MÁXIMO DA SILVA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1115, '2359061', 'FERNANDA NORA DE OLIVEIRA CASTILHEIRO', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1116, '2278332', 'ATAIRDO ADRIEL MOREIRA CUNHA FILHO', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1117, '2275263', 'DOUGLAS DE SALES BATISTA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1118, '2283889', 'ISABELLY VITORIA DA SILVA MORAIS', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1119, '2273767', 'JOÃO ANTONIO DIAMANTE DA CRUZ', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1120, '2297095', 'JONATHAN BRAZ MACIEL', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1121, '2298064', 'JOSE AUGUSTO SEBA PEREIRA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1122, '2174958', 'JULIANY JULISTER FERREIRA ALVES', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1123, '2313739', 'KETTELY DA SILVA MATIAS', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1124, '2538135', 'KEVEN BENEDITO RODRIGUES DE BRITO', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1125, '2626697', 'LAUANY VITORIA DA SILVA SANTOS CARDOZO', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1126, '2623125', 'LORENA SCHIRLO SCHRAIBER', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1127, '2289974', 'MELLYSSA ADAN DE SOUSA ARRUDA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1128, '2277974', 'YASMIM SALVATIERRA DO NASCIMENTO PEREIRA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1129, '2385515', 'BRUNA VITORIA CHAGAS COSTA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1130, '1897938', 'EMILAYNE ELOÁ DOS SANTOS CARDOSO DE OLIVEIRA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1131, '1912185', 'MARIA ELISA ARAUJO DE OLIVEIRA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1132, '2109626', 'PEDRO MIGUEL RODRIGUES', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1133, '1978483', 'EMANUELLY PEREIRA DA SILVA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1134, '1783538', 'GRAZIELLI OLIVEIRA DA SILVA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1135, '2393968', 'IGOR GABRIEL COSTA FERRAZ', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1136, '2287251', 'MARIA CLARA ALVES DE ALMEIDA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1137, '2341453', 'EMILY ALEXANDRA SILVA DOS SANTOS', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1138, '2601076', 'MARIA DO CARMO FIALHO DE ARRUDA NETA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1139, '2191554', 'SOPHIA DA SILVA MACIEL', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1140, '2319210', 'AYUME IASMYN SANTOS DE JESUS', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1141, '1755314', 'ISABELA DE SOUZA TARCIEL', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1142, '2276974', 'HELOYSA DA SILVA OLIVEIRA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1143, '2334408', 'ANA JULIA DIAS DE ALMEIDA', false, '2º Ano Ciências Humanas D', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1144, '2145234', 'LUCAS HENRIQUE VIEIRA SANTANA RIBEIRO BARBOSA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1145, '2299273', 'MARIA EDUARDA COSTA ALMEIDA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1146, '2280871', 'PEDRO GUSTAVO SOARES DA SILVA BRITO', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1147, '2276325', 'RYAN PABLO OLIVEIRA DE SOUZA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1148, '2297264', 'MARIA EDUARDA DE CAMPOS MIRANDA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1149, '2275937', 'MARIANNY FERNANDA AMORIM SUDRÉ', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1150, '2660322', 'MIGUEL FELIPE ALVES FERREIRA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1151, '2297528', 'MILLENY KEMILLY SILVA PEREIRA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1152, '2297544', 'MYKAEL RENAN SILVA MATOS', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1153, '2278119', 'NATALIA CAMPOS AKERLEY', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1154, '2623684', 'PEDRO HENRIQUE RAMOS OLIVEIRA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1155, '2282192', 'RAYANNE BARBOSA DE ALMEIDA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1156, '2314008', 'ROBERTO DA SILVA GONZAGA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1157, '1900180', 'RYAN MATHEUS DA SILVA SOUZA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1158, '2329175', 'THÁCYLA DUARTE OLIVEIRA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1159, '2314317', 'THAYNA EMANUELE SILVA SENE', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1160, '2277883', 'ANDRIELLY SANTANA LEITE DA SILVA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1161, '2227024', 'ANTHONNY SERGIO AMORIM DE ALMEIDA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1162, '2297988', 'AVANILDO SANTANA DOS SANTOS FILHO', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1163, '2532200', 'BRENO EDUARDO DE OLIVEIRA SILVA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1164, '2167606', 'EDUARDO DONALIS OLIVEIRA DA SILVA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1165, '2282049', 'EMANUELLY RAUANA CONCEIÇÃO DA SILVA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1166, '2637798', 'FELIPE GABRIEL ALVES DA SILVA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1167, '1976620', 'HAITHAN GUILHERME MORAES DE SOUZA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1168, '2282110', 'HENRIQUE BARBOSA DE ALMEIDA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1169, '1933510', 'HIGOR MIGUEL FERREIRA GAMA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1170, '2454282', 'ÍTALLA STEFANY MORAES DA COSTA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1171, '2308725', 'LUDMILA SANTOS DE OLIVEIRA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1172, '1912723', 'GABRIEL NICOLAI DE CAMPOS', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1173, '2285346', 'JOÃO VICTOR SURUBI DA ROCHA', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1174, '2137292', 'GUSTAVO DA COSTA SEVERO', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1175, '1900402', 'KAYO HITOSHI SHIMA YAGI', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1176, '2275308', 'MIGUEL APARECIDO PEREIRA DE CAMPOS', false, '2º Ano Ciências da Natureza E', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1177, '2210722', 'MARCOS VINICIUS FERREIRA MENDES DA SILVA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1178, '2631488', 'LIGIA JOANA SILVA PEREIRA LEITE', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1179, '2362314', 'ÉRIC LUIZ OLIVEIRA VIEIRA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1180, '2299388', 'MARIA EDUARDA SOUZA SILVA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1181, '2362261', 'MARIA FERNANDA SILVA GONÇALVES', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1182, '2297437', 'MARIA RITA CURVO DE OLIVEIRA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1183, '2281529', 'PAULO CESAR JESUS DA SILVA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1184, '1973016', 'RAILLA GABRIELA DA SILVA SOUZA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1185, '2248408', 'SARAH REGINA DA COSTA SANTOS', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1186, '1971220', 'VITORIA CRISTINA GUIMARAES GOMES', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1187, '2275410', 'WALLACE PATRICK DA SILVA BASTOS', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1188, '2282724', 'YURY RODRIGO SILVA MARTINS', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1189, '2010715', 'FABIO HENZO CAMPOS DA COSTA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1190, '2278654', 'WELLIGTON JUNIOR BATISTA SARMENTO', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1191, '2372581', 'KAMILLY DE OLIVEIRA DUARTE', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1192, '2299406', 'NÍCOLAS EDUARDO DE OLIVEIRA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1193, '2297562', 'PHELIPE GABRIEL TEIXEIRA LARA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1194, '2298334', 'VITOR HUGO SOUZA DE CAMPOS', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1195, '2310534', 'ROSVALDO FERREIRA DA SILVA JUNIOR', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1196, '2344517', 'WENDER GABRIEL DUARTE DE SOUZA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1197, '2463799', 'SARAH GABRIELY RODRIGUES ZEMKE', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1198, '2268412', 'KÉTURY FIGUEIREDO RODRIGUES', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1199, '2182966', 'STEFANY VITÓRIA CORREIA DA SILVA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1200, '2266848', 'HELOÍSA COSTA DE OLIVEIRA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio') ON CONFLICT (id) DO NOTHING;

INSERT INTO students (id, cod, nome, paed, turma, turno, serie, curso, modalidade) VALUES 
(1201, '2131844', 'ARIELLY APARECIDA CAMPOS DE OLIVEIRA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1202, '2241953', 'RYAN FELIPE SILVA DE OLIVEIRA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1203, '2555644', 'ROBSON LUCAS COSTA DE CAMPOS', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1204, '2282184', 'PEDRO DIOGO UNTAR DA SILVA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1205, '2226086', 'ISABELLA RIOS DE FARIA LOPES', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1206, '2246185', 'MARIA CECÍLIA DA COSTA FERREIRA', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1207, '2526255', 'RAFAELLA VITORIA FERREIRA SANTOS', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1208, '2261811', 'CINTIA REGINA CORREA DO NASCIMENTO', false, '2º Ano Ciências da Natureza F', 'Matutino', '2º Ano', 'Médio', 'Médio'),
(1209, '2289477', 'LUCAS GABRIEL ALMEIDA DA SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1210, '2275463', 'GEOVAN GABRIEL DA SILVA GONÇALVES', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1211, '2172235', 'ARYANE SILVA DE MELO', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1212, '1931410', 'ANELISE DOS SANTOS MAGALHAES', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1213, '2282431', 'ANI BEATRIZ LOPES ESTEVAO DA SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1214, '2597525', 'BRYAN CRISTHIAN HURTADO DIAS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1215, '1875519', 'EDUARDO KAYTTO DE ALMEIDA OLIVEIRA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1216, '2289617', 'EMERSON FERREIRA COELHO DE ALMEIDA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1217, '2635841', 'GABRIELLE STEFANNE DA SILVA CAMPOS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1218, '2358421', 'GUILHERME DE JESUS DA SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1219, '2281244', 'GUILHERME FIGUEIREDO DA SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1220, '2631464', 'HELOISA MONIKE OLIVEIRA LEMES', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1221, '2596495', 'HENZO GUILHERMY SANTOS DE MORAES', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1222, '2076365', 'JOAO GABRIEL RODRIGUES', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1223, '2374878', 'JOAO GABRIEL SOUZA COSTA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1224, '2262648', 'JOSUÉ HENRIQUE CAMPOS SOARES', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1225, '2557588', 'JULIANA DA SILVA SOUZA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1226, '1874118', 'MARIA EDUARDA PIZOTO CASAGRANDE', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1227, '1809092', 'MARIA LUIZA FELIX MAITAN', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1228, '2603723', 'OTAVIO AUGUSTO DE SOUZA HURTADO', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1229, '2360526', 'PEDRO RAFAEL FONTOURA BARROS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1230, '2280956', 'RAISSA GABRIELA COSTA RAMOS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1231, '2552109', 'THACIO CRISTIANO ABREU SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1232, '2601361', 'THALLES HENRICK FROZZA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1233, '2604883', 'VICTOR GABRIEL OLIVEIRA DUARTE', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1234, '1976313', 'YASMIN BATISTA FERREIRA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1235, '2058573', 'ALISSON BRUNO LUIZ MARTINS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1236, '2243831', 'EMILLY VITÓRIA SOUZA DE ALMEIDA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1237, '2601175', 'THALYSON GUILHERME ALVES BARBOSA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1238, '2125265', 'ARTHUR ESCOBAR MARCOS MASCARENHAS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1239, '2125267', 'BEATRIZ ESCOBAR MARCOS MASCARENHAS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1240, '2547410', 'MOISES KAIKE PEREIRA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1241, '2229560', 'BRENO VINICIUS DA CUNHA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1242, '1684809', 'CARLOS EDUARDO NASCIMENTO SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1243, '2144476', 'GUSTAVO HENRIQUE SANTOS LAVIOLA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1244, '2330584', 'GABRIELLY BEATRIZ ROSA NASCIMENTO', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1245, '2276049', 'LUCAS RYAN AREVALO LIPÚ MASSAVI', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1246, '2275892', 'ERIK DA SILVA MARTINS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1247, '2540852', 'MANUELA GRAZIANI PESSOA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1248, '2307632', 'RAFAEL TOMAZ DE ASSIS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1249, '2276923', 'LUIZ EDUARDO RAMOS DA SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1250, '2276790', 'ADRIAN CARDOSO PAULA DA SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1251, '2304756', 'OTAVIO DA COSTA ILARIO', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1252, '2133348', 'JAIRO KAWÃ APARECIDO DOS ANJOS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1253, '2000971', 'RAFAEL HENRIQUE RIBEIRO DA SILVA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1254, '2481685', 'ALEXANDRE LUIS DE SOUZA BARRETO', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1255, '2035101', 'PAULO HENRIQUE FERREIRA CUNHA', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1256, '2409101', 'KAWAN MYQUEIAS ALEXANDRE MAGALHAES DOS SANTOS', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1257, '2278683', 'ANA VITÓRIA ALVES MAZETO', false, '2º Ano Noturno G', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1258, '2659715', 'ABRAAO HENRIQUE OLIVEIRA LEITE', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1259, '1970693', 'ARTHUR ALVES PEREIRA DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1260, '2601022', 'CARLOS HENRIQUE MAGALHAES DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1261, '2628244', 'CARLOS HENRIQUE MOREIRA DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1262, '2023222', 'CLAYTON ANDRADE GOMES DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1263, '2566994', 'GEOVANE ARMANDO DA SILVA SOARES', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1264, '2604899', 'GUSTAVO FECHTNER CORREA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1265, '2442663', 'JOÃO GABRIEL MARQUES DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1266, '2246961', 'LAYSA DE OLIVEIRA DOMICIANO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1267, '2374384', 'LEONARDO ARAUJO DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1268, '2275387', 'LEONILDO DA SILVA SOUSA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1269, '2275767', 'LUIS FELIPE PEREIRA DA COSTA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1270, '2499141', 'MAINARA LARYSSA DA SILVA FREITAS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1271, '2150736', 'MARCEL CRISTHIAN GOMES BALIEIRO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1272, '2362076', 'MARCOS VINICIOS ALVES DE SOUZA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1273, '2274870', 'MARCOS VINICIUS PINTO DE BRITO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1274, '2257020', 'PEDRO HENRIQUE DIEHL LOPES', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1275, '2173904', 'SARAH GABRIELLY ALMEIDA MENDES', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1276, '2052492', 'THAYSA CHRISTINE DA SILVA MIRANDA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1277, '2275832', 'VERÔNICA AREVALO LIPÚ DE JESUS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1278, '1878984', 'ENDY VITORIA WUDARSKI RUDENAS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1279, '2297243', 'LUIGI GABRIEL DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1280, '1801641', 'KAUAN JESUS LOPES SANTOS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1281, '2134861', 'SARAH LIVIA FIGUEIREDO SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1282, '1750610', 'KEMILLY DE FREITAS QUEROZ', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1283, '2112787', 'DANIEL GODOY DE OLIVEIRA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1284, '2274600', 'ANA BELLA DOS SANTOS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1285, '2375350', 'MYCHELL MAGALHÃES DE ALMEIDA LEMES', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1286, '2370740', 'KAUA BRASILEIRO BRITO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1287, '2137097', 'LUÍS GUILHERME DE CAMPOS NASCIMENTO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1288, '2305459', 'LUCAS VINICIUS SILVA NASCIMENTO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1289, '2291409', 'ANTÔNIO CARLOS SOUZA JESUS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1290, '2246156', 'ANA CLARA GONÇALVES DOS SANTOS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1291, '2276507', 'JOÃO GABRIEL DE ARRUDA DOS SANTOS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1292, '2414686', 'YURI ANTONIO MARQUES SOARES', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1293, '2233808', 'LARYSSA VICTÓRIA BARROS DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1294, '2299617', 'DAVI BATISTA DE SOUZA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1295, '1894734', 'LUIS FERNANDO NEVES DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1296, '1982774', 'ILDEBRANDO RODRIGUES DE MORAES FILHO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1297, '2376186', 'EDSON VILHALVA OLIVEIRA DA GUIA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1298, '2276721', 'MARIA CLARA DO NASCIMENTO MARQUEZINI', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1299, '2289454', 'YAN FERNANDO DE OLIVEIRA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1300, '2343466', 'JOAO EMANUEL APARECIDO RIBEIRO DE ARAUJO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1301, '2143376', 'PEDRO HENRIQUE DE MORAIS AMORIM ESPIRITO SANTO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1302, '1867137', 'GUSTAVO RODRIGUES DOS SANTOS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1303, '2123180', 'ÁGHATA DE CAMPOS FIGUEIREDO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1304, '2637534', 'LEONARDO DOMINGOS PINHO DA CRUZ', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1305, '2326589', 'DURVAL ANGELINO DA COSTA JHUNNIOR', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1306, '2731850', 'ANTHONI RAFAEL NAVARRO TESSARO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1307, '1705837', 'RYAN KAIKE DA SILVA FERREIRA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1308, '2133652', 'ANA BEATRIZ LIRA DOS SANTOS', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1309, '2479799', 'JOAO GABRIEL DA SILVA', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1310, '1724907', 'MARIA VITORIA ASSIS RIBEIRO', false, '2º Ano Noturno H', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1311, '1921610', 'KESIA PAMELA OLIVEIRA SOUZA', false, '2º Ano Noturno I', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1312, '2031160', 'PEDRO HENRIQUE SOARES SILVA', false, '2º Ano Noturno I', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1313, '1978327', 'VICTOR HUGO DIAS DE PORTUGAL', true, '2º Ano Noturno I', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1314, '1898232', 'FELIPE GABRIEL BRITO AMORIM', false, '2º Ano Noturno I', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1315, '1936050', 'EMANUELLI DA SILVA MIRANDA', false, '2º Ano Noturno I', 'Noturno', '2º Ano', 'Médio', 'Médio'),
(1316, '2701549', 'DELIANNYS DEL CARMEN SANTIAGO GUAINA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1317, '2245009', 'TAYLA LORRAYNNY DA SILVA SANTOS', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1318, '2259374', 'ALISSON ALEXANDRE SILVA CARDOSO', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1319, '1897157', 'ANA JULIA DE DEUS OLIVEIRA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1320, '2226137', 'EMILLY VITORIA COSTA AMORIM', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1321, '2256984', 'MIGUEL MARQUES MARCOSKI', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1322, '2261613', 'NATHÁLIA CRISTINA MARQUES DA COSTA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1323, '2108076', 'THAUANY LOHANY RIBEIRO DE LIMA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1324, '2227805', 'ANA GABRIELE GOMES DA CRUZ', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1325, '2251905', 'EMANUELLY DE OLIVEIRA LIMA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1326, '1883304', 'EMILLY DA SILVA PENA FIEL', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1327, '2224905', 'EMILLY KAROLAINE FARIA DE OLIVEIRA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1328, '2142368', 'MARIA EDUARDA LINO DA SILVA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1329, '2399848', 'MARIA LUIZA DE ASSIS ROCHA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1330, '2257869', 'NATHAN VICTOR DE CAMPOS E SILVA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1331, '2048494', 'OLAVO HENRIQUE TABORY BORGES', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1332, '2225829', 'ADENILSON LUCAS DE ALMEIDA CAMPOS', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1333, '2044314', 'ARTHUR MARINHO FALCÃO PEREIRA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1334, '2524594', 'EDILAINE DA SILVA VIEIRA REIS', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1335, '2216747', 'EVERSON RAYEL MOREIRA DA CRUZ', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1336, '1933050', 'JEFFERSON MICHEL DE SOUZA FERREIRA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1337, '2216093', 'JEOVAN MAGALHÃES DE SENE', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1338, '2260710', 'KAMYLLA VITORIA CRUZ NEITZEL', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1339, '2192779', 'SAMYRA NUNES DE ALMEIDA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1340, '2216047', 'VINICIUS HENRIQUE DA SILVA RIGOL', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1341, '2140785', 'ALINE DE ASSIS FERREIRA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1342, '2223844', 'KAMILLA SANTANA FEITOSA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1343, '2519610', 'JOAO VICTOR GOMES', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1344, '2244321', 'THÉO LEITE MARCONDES', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1345, '2225084', 'JOÃO PEDRO DA CUNHA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1346, '1861892', 'KETHILLY NATHÁLLIA DA SILVA TEIXEIRA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1347, '2240715', 'MARIA PAULA DA SILVA BUENO', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1348, '2356520', 'ANA ESTER BARBOSA BATISTA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1349, '2543208', 'JHON CLÉCIO PEREIRA DA SILVA', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1350, '2453760', 'PYETRO BARROS DE ALBUQUERQUE', false, '3º Ano Linguagens A', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1351, '2052586', 'GUSTAVO ANTÔNIO COSTA DA SILVA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1352, '2002370', 'PEDRO LUCAS NASCIMENTO DA SILVA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1353, '2363816', 'ANDREI FERNANDO ALVES DE AMORIM', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1354, '2382453', 'REINALDO PAULO CRISOSTOMO FILHO', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1355, '1764097', 'VICTOR HUGO CAMPOS DE MORAES', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1356, '2251598', 'JUAN DA SILVA ALMEIDA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1357, '2471934', 'EMANUEL GUILHERME LOPES DE ALMEIDA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1358, '2284745', 'EVERTON GABRIEL CATARINO GREGORIO', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1359, '2164111', 'LUIZ MIGUEL RIBEIRO SANTOS', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1360, '2375428', 'ELLEWELSON CRISTHIAN GONCALVES DA SILVA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1361, '1890606', 'IGOR TAPAJÓS DA SILVA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1362, '2725878', 'RYAN TORRES RIBEIRO', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1363, '2123191', 'MARIO EDUARDO MARTINS DA SILVA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1364, '2251864', 'GABRIEL ALVES GONÇALVES', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1365, '1921771', 'ARIEL PEREIRA FORMIGHIERI', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1366, '2254990', 'ALYSSON AMARAL LEITE', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1367, '2727040', 'CAIO LUCAS SAMPAIO DE SOUZA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1368, '2064341', 'ELIZANDRO RODRIGUES DA SILVA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1369, '1619279', 'DULCE MARIA DE SOUZA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1370, '2050321', 'JOÃO GABRIEL MORAIS DA SILVA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1371, '1686343', 'ANDRE LUIZ FIGUEIREDO ARAUJO', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1372, '2152683', 'REBECA LECINA FERREIRA DE ALVARENGA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1373, '2261872', 'IONDA ONÓRIO DE LIMA CAMPOS', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1374, '2085230', 'VICTOR GABRIEL COSTA SILVA', true, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1375, '1880762', 'HELOISA DE SOUZA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1376, '2465371', 'PETERSON SILVA DE SOUZA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1377, '2042447', 'MATEUS GONÇALVES MARINHO DA COSTA', false, '3º Ano PRA A', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1378, '2095496', 'KAREN AMANDA DA SILVA TENÓRIO', false, '3º Ano PRA B', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1379, '2220232', 'ANA VITÓRIA SILVA DE ALMEIDA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1380, '2224565', 'ARTHUR MIGUEL OLIVEIRA ALVES', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1381, '2230795', 'ESTELA GOMES ALMEIDA SILVA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1382, '2218132', 'HEITOR FERREIRA DE SOUZA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1386, '2546838', 'THALYA BARBOSA DE SOUZA ALENCAR', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1387, '2233209', 'VITOR TORQUATO DE MACEDO', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1388, '2345722', 'ANA CECÍLIA RODRIGUES DA SILVA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1389, '2217292', 'ANA JÚLIA PONTES DA SILVA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1390, '2215835', 'ANNA JULIA COSTA DO ESPIRITO SANTO', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1391, '2216671', 'ANNA JULYA DOS SANTOS RODRIGUES', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1392, '2244529', 'BRUNA RAKELY OLIVEIRA CORREA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1393, '2382397', 'DEYVS RIBEIRO GOMES', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1394, '2226984', 'EDSON FRANCISCO PEREIRA SUTTER DA CRUZ', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1395, '2136051', 'ELLEN VITÓRIA AZEVEDO LEMES', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1396, '2231457', 'GUYLHERME OLIVEIRA DE MORAES', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1397, '2012206', 'HEVELLYN NOGUEIRA NOVAIS', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1398, '2536096', 'KAUÃ HENRIQUE CHESSMAN DA SILVA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1399, '2221756', 'KAUE VEDOI EUFRASIO', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1400, '2172213', 'LEONARDO GABRIEL CUNHA DE OLIVEIRA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1401, '1802480', 'LEONARDO LEAL JOANE DA SILVEIRA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1402, '2216402', 'MIUCKY LORRAINY SILVA ARRUDA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1403, '1818606', 'NOEMILLY VICTÓRIA FERREIRA BASTOS', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio') ON CONFLICT (id) DO NOTHING;

INSERT INTO students (id, cod, nome, paed, turma, turno, serie, curso, modalidade) VALUES 
(1404, '2513252', 'VITÓRIA PEDRO ALVES', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1405, '2222001', 'ALLAN GABRIEL MIRANDA SILVA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1406, '1755070', 'DENNER GABRIEL SANTOS SILVA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1407, '2218065', 'NICOLLY THAYANY DA SILVA COSTA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1408, '2261951', 'LORENA EORANY DA SILVA PERIS', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1409, '2235541', 'LUCAS FRANCISCO PENHA CUSTÓDIO', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1410, '1770153', 'ANA LIVIA GONÇALVES DE ARRUDA', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1411, '2317033', 'YURI FELIPE OLIVEIRA DA CONCEIÇÃO', false, '3º Ano Ciências Humanas B', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1412, '2261975', 'CARLA APARECIDA OLIVEIRA SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1413, '2339942', 'CAROLINI VITORIA FORMIGHIERI ARAUJO', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1414, '2035668', 'ISADORA PRADO DE OLIVEIRA BOTELHO', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1415, '1867741', 'JOÃO GABRIEL DE MORAES COSTA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1416, '2218023', 'JOÃO MIGUEL GOES SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1417, '2218133', 'JULIA CAVALCANTE CRUZ', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1418, '2042911', 'KAUANY MONTEIRO MENDES', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1419, '2279919', 'LUIZ FERNANDO PRADO SANTANA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1420, '2246999', 'MONALISA VITORIA PEREIRA DO CARMO', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1421, '2063263', 'PAULO CESAR CAMPOS RIBEIRO', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1422, '2217840', 'RAYSSA CHRISTINE MENEZES DA SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1423, '2630207', 'SAVIO RODRIGUES DA SILVA AMORIM', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1424, '2224432', 'MADELY ELIZABETH DE ARRUDA SANTOS', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1425, '2299245', 'MYRIAN ARAUJO DA SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1426, '2292236', 'RAFAELA DE ARRUDA FURTUOSO', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1427, '2261562', 'RAYSSA NAWANI MARIA MORAES DA SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1428, '2222250', 'JOÃO VICTOR FARIAS', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1429, '2189779', 'YNARIAN SALETTE DELFINA MARCOSKI FORTES FERRAZ', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1430, '2399025', 'GIOVANNA SOUZA TAQUES', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1431, '2195551', 'HELOÍSA BARBOSA THOMAZ', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1432, '2038000', 'IARAH JULIANA SILVA DE CAMPOS', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1433, '2241839', 'AARON FRANCISCO SANTOS ACEL', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1434, '2519454', 'VITOR GABRIEL MOLITOR CARPES', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1435, '1777263', 'GUILHERME FERREIRA GUSMÃO', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1436, '2730076', 'REBEKA WILIONNAY DA ROCHA SANTOS', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1437, '1638521', 'DIEGO MACIEL DE AMORIM', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1438, '2174960', 'LAUANNY MANOELY NERES DA SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1439, '2519680', 'MARIA CLARA DE CAMPOS SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1440, '2049605', 'PEUTRA RAYANI ROCHA FERREIRA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1441, '2529601', 'LUCAS SANTOS ARAÚJO SCHMOELLER', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1442, '2299041', 'LETÍCIA MACIEL DA SILVA', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1443, '2247621', 'VICTOR HENRIQUE BALBUENO', false, '3º Ano Ciências Humanas C', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1444, '2145400', 'KEVILLY VICTORIA DE SOUZA NEVES', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1445, '2221639', 'AMANDA VITORIA RODRIGUES DE OLIVEIRA', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1446, '2519509', 'ANA MARIA LEMES DE MORAES', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1447, '2532525', 'EDUARDA ARRUDA VIÉGAS', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1448, '1861631', 'JOAO FRANCISCO NASCIMENTO VIEIRA LUZ', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1449, '1933612', 'NICOLLY FERREIRA LOPES DA SILVA', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1450, '2519319', 'PAULO HENRIQUE PIRES DA COSTA', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1451, '2247017', 'THIAGO JOSE DE CAMPOS SILVA', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1452, '1760431', 'THIAGO JUNIO SOUZA COSTA', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1453, '1971860', 'WERENCK REINALDO FERRAZ', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1454, '2132703', 'ADENIELSON DA SILVA SOUZA FERRO', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1455, '2315904', 'ANA CLAUDIA NUNES BARBOSA', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1456, '2246883', 'ALLANA SILVA MENDES VIEIRA', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1457, '2222398', 'ANA BEATRHIZ DE ARRUDA MARQUEZINI', false, '3º Ano Técnico Gestão D', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1458, '2547647', 'RHAFAEL MORAES DA SILVA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1459, '2398218', 'ALESSANDRO MIGUEL BEZERRA DOS SANTOS', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1460, '2277720', 'CAIO ROBERTO DA SILVA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1461, '2364569', 'DEBORA VITORIA MARQUES PICONI', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1462, '2143030', 'EMANUELLE BEATRIZ DE ARRUDA E SILVA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1463, '2533967', 'ERICKY GONÇALVES DE CAMPOS', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1464, '1916605', 'GABRIEL MARCONY MARTINS DE ALENCAR', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1465, '2533952', 'GABRIELLY LARISSA DE CAMPOS SILVA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1466, '2547615', 'HELOÁ CRISTYNY DA SILVA ARRUDA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1467, '2247057', 'JOÃO VINICIUS JESUS DO NASCIMENTO', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1468, '2519490', 'JULIANE APARECIDA SILVA SANTANA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1469, '2364457', 'JULLIA OSERIMAGBO SOARES SEIXAS PEREIRA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1470, '1921612', 'KEREN HAPUKE VITORIA OLIVEIRA CARVALHO', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1471, '2217606', 'LAYS MARIA GONÇALVES MARTINS', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1472, '2547594', 'MARIA EDUARDA DA SILVA QUEIROZ', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1473, '2137210', 'MARIA JÚLIA DE MELO SOUZA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1474, '2228165', 'MARIAH CLARA DA SILVA FRANÇA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1475, '2313499', 'NAYARA CRISTINA GONÇALVES RIBEIRO', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1476, '2217135', 'BRAIAN BARBOSA DA SILVA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1477, '2511345', 'ERICK MATHEUS MORAES DE ARRUDA', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1478, '1925592', 'VITÓRIA ELOÁ DA SILVA HEIDMAN', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1479, '1786567', 'KAROLAINE GONCALVES DA SILVA MELLO', false, '3º Ano Técnico Web Design E', 'Matutino', '3º Ano', 'Médio', 'Médio'),
(1480, '2257446', 'MARIA CLARA DE OLIVEIRA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1481, '2234947', 'ANDRÉ WINICIUS RONDON DE ALCÂNTARA GONÇALVES', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1482, '2123798', 'CAMILI VITORIA SANTOS DE OLIVEIRA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1483, '2245747', 'GIOVANNA VITÓRIA DE CAMPOS', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1484, '2218104', 'JOÃO GUILHERME LEMES DE SOUZA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1485, '2250338', 'KAMILLA KÁSSIA FONTOURA BARROS', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1486, '1938140', 'KAMMILLY VICTORIA DE CAMPOS RIBEIRO', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1487, '2442438', 'KELVIN RICARDO DE SOUZA DIAS', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1488, '2554131', 'MARISOL LEMES DA SILVA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1489, '2230693', 'RIANN GABRIEL SANTANA DA SILVA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1490, '2133097', 'VANESSA CRISTINA MARQUES SAMBUGARI', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1491, '2057488', 'ANA JULIA CONCEIÇÃO SILVA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1492, '2251206', 'VINICIUS GUSTAVO DIAS DE ARRUDA COSTA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1493, '2138175', 'JAMILY LUCIA DA SILVA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1494, '2413056', 'WINICIUS RODRIGUES PARISE', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1495, '2109691', 'CRISTIAN LUIZ GUIMARÃES DOS SANTOS', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1496, '2293345', 'EZEQUIEL RODRIGUES NASCIMENTO DE MORAIS', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1497, '1649397', 'ANA JULIA DA SILVA OLIVEIRA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1498, '1884427', 'EMILLY VITÓRIA RODRIGUES PLETSCH', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1499, '2514007', 'TAMIRIS JULIANI DA CRUZ CAMPOS DUCA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1500, '2442512', 'KAYLANE GABRIELLE GUIMARÃES SILVA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1501, '2050990', 'RAONI MOREIRA MESQUITA LEÃO', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1502, '2282420', 'STEFFANY AMANDA SANTANA SILVA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1503, '2459622', 'KYARA NEVES GODOY CARRÍJO', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1504, '2246680', 'CARLOS EDUARDO ANTUNES QUEIROZ', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1505, '2417734', 'RAKELLY EMANUELLY DE MORAES NASCIMENTO', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1506, '2124262', 'MARIA JULIA DE OLIVEIRA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1507, '2219544', 'LUIZ GUSTAVO SILVA DANTAS', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1508, '2291369', 'NICOLAS DA HORA NUNES', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1509, '2519518', 'ISABELLY STHEFANI DE OLIVEIRA BARBOSA', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1510, '1803645', 'RYAN RIBEIRO DE FIGUEIREDO', false, '3º Ano Técnico Gestão F', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1511, '2519285', 'VITOR MARIANO SILVA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1512, '2554783', 'ALEXANDRE JOSE DA SILVA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1513, '2526478', 'ANA GABRIELLY PEREIRA DE MORAES', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1514, '2220915', 'ANGELINA SILVA DE ALMEIDA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1515, '2012687', 'FLAVIO LEITE DOS SANTOS', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1516, '2276802', 'GUSTAVO DA SILVA MORAIS DIAS DE OLIVEIRA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1517, '2153894', 'GUSTAVO NEGRISOLI RODRIGUES DE SOUZA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1518, '2536342', 'IGOR GOMES DOS SANTOS', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1519, '2053942', 'ITALO ALVES DE SOUZA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1520, '1809114', 'JELDER LUIS DE ALMEIDA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1521, '2425212', 'KAROLINE DANIELLA DE OLIVEIRA PRADO', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1522, '1973298', 'LUIZ GABRIEL DA SILVA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1523, '1748133', 'RAFAEL EDUARDO GALDINO DE SOUZA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1524, '2228743', 'RENATO HEITOR PAIVA JORGE', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1525, '2491613', 'TABITTA MARTINS SOUZA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1526, '2543729', 'THAMARA DANYELY FREITAS SOUZA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1527, '2535911', 'THAWANNY DA SILVA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1528, '1972074', 'WESLEY DE SOUZA SANTANA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1529, '1780181', 'LUCAS DA SILVA SOUZA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1530, '2314017', 'PIETRO MATIAS MARTINS FONSECA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1531, '2156203', 'LUAN MARQUES RODRIGUES GOMES', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1532, '2217733', 'RICHARD ALVES DE CARVALHO', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1533, '2223099', 'MARCIONEI DE OLIVEIRA MENDES', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1534, '1908462', 'GABRIELA GARCIA FAVERO', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1535, '2216141', 'LUANNA GABRIELLA EIDAN SILVA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1536, '1754905', 'LUCAS LIMA BUSTAMANTE', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1537, '2246697', 'JOÃO VICTOR CASTRILLON SANTANA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1538, '2020174', 'JONATHAN GUSTAVO FERNANDES CAMPOS', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio'),
(1539, '2233813', 'NICOLLAS GABRIEL DE OLIVEIRA', false, '3º Ano Técnico Web Design G', 'Noturno', '3º Ano', 'Médio', 'Médio') ON CONFLICT (id) DO NOTHING;

-- Classificações existentes
INSERT INTO classifications (student_id, class_id) VALUES (4, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (4, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (4, 'acompanhamento');
INSERT INTO classifications (student_id, class_id) VALUES (4, 'paedaee');
INSERT INTO classifications (student_id, class_id) VALUES (5, 'acompanhamento');
INSERT INTO classifications (student_id, class_id) VALUES (1511, 'abaixo');
INSERT INTO classifications (student_id, class_id) VALUES (1511, 'acompanhamento');
INSERT INTO classifications (student_id, class_id) VALUES (1511, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (1511, 'paedaee');
INSERT INTO classifications (student_id, class_id) VALUES (1512, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (1512, 'socioemocional');
INSERT INTO classifications (student_id, class_id) VALUES (1513, 'acompanhamento');
INSERT INTO classifications (student_id, class_id) VALUES (1513, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (12, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (12, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (13, 'paedaee');
INSERT INTO classifications (student_id, class_id) VALUES (13, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (14, 'evasao');
INSERT INTO classifications (student_id, class_id) VALUES (15, 'socioemocional');
INSERT INTO classifications (student_id, class_id) VALUES (19, 'faltoso');
INSERT INTO classifications (student_id, class_id) VALUES (19, 'abaixo');
INSERT INTO classifications (student_id, class_id) VALUES (20, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (20, 'acompanhamento');
INSERT INTO classifications (student_id, class_id) VALUES (21, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (21, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (21, 'socioemocional');
INSERT INTO classifications (student_id, class_id) VALUES (22, 'paedaee');
INSERT INTO classifications (student_id, class_id) VALUES (22, 'socioemocional');
INSERT INTO classifications (student_id, class_id) VALUES (22, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (17, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (24, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (24, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (25, 'evasao');
INSERT INTO classifications (student_id, class_id) VALUES (25, 'paedaee');
INSERT INTO classifications (student_id, class_id) VALUES (25, 'socioemocional');
INSERT INTO classifications (student_id, class_id) VALUES (27, 'socioemocional');
INSERT INTO classifications (student_id, class_id) VALUES (27, 'destaque');
INSERT INTO classifications (student_id, class_id) VALUES (29, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (29, 'acompanhamento');
INSERT INTO classifications (student_id, class_id) VALUES (6, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (7, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (8, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (9, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (10, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (11, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (13, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (14, 'media');
INSERT INTO classifications (student_id, class_id) VALUES (4, 'faltoso');

-- Observações existentes
INSERT INTO observacoes (student_id, texto) VALUES (30, 'teste');
INSERT INTO observacoes (student_id, texto) VALUES (31, 'teste');
INSERT INTO observacoes (student_id, texto) VALUES (32, 'teste');
INSERT INTO observacoes (student_id, texto) VALUES (4, 'teste');
INSERT INTO observacoes (student_id, texto) VALUES (4, 'teste');
INSERT INTO observacoes (student_id, texto) VALUES (6, 'teste');
INSERT INTO observacoes (student_id, texto) VALUES (10, 'teste');
INSERT INTO observacoes (student_id, texto) VALUES (16, 'teste');

-- Encaminhamentos existentes
INSERT INTO encaminhamentos (student_id, texto) VALUES (31, 'teste');
INSERT INTO encaminhamentos (student_id, texto) VALUES (4, 'teste');
INSERT INTO encaminhamentos (student_id, texto) VALUES (7, 'teste');
INSERT INTO encaminhamentos (student_id, texto) VALUES (9, 'teste');

SELECT setval('students_id_seq', (SELECT COALESCE(MAX(id), 1) FROM students));
SELECT setval('turmas_id_seq', (SELECT COALESCE(MAX(id), 1) FROM turmas));

